# Generated by Django 4.2.4 on 2023-12-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0004_alter_mathcourse_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodule',
            name='module_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mathcourse',
            name='course_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
