# Generated by Django 4.2.4 on 2023-12-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0005_coursemodule_module_image_lecture_lecture_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='module_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
