# Generated by Django 4.2.4 on 2023-12-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0006_alter_coursemodule_module_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathcourse',
            name='course_image',
            field=models.ImageField(null=True, upload_to='mathCourseImg/'),
        ),
    ]
