# Generated by Django 4.2.4 on 2023-12-03 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0009_alter_mathcourse_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathcourse',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CommonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550, null=True)),
                ('question', models.CharField(max_length=1050, null=True)),
                ('image', models.ImageField(null=True, upload_to='questionImg/')),
                ('answer', models.CharField(verbose_name=550)),
                ('explanation', models.TextField(null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminMathTrainer.lecture')),
            ],
        ),
    ]
