# Generated by Django 4.2.4 on 2023-12-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0010_mathcourse_price_commontest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathcourse',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
