# Generated by Django 4.2.4 on 2023-12-03 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0011_alter_mathcourse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathcourse',
            name='course_user',
            field=models.ManyToManyField(related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
