# Generated by Django 4.2.4 on 2023-12-08 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0012_mathcourse_course_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathcourse',
            name='course_discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='mathcourse',
            name='course_length',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
