# Generated by Django 4.2.4 on 2023-12-08 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0013_mathcourse_course_discount_mathcourse_course_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminMathTrainer.mathcourse')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
