# Generated by Django 4.2.4 on 2023-12-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0014_courserate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathcourse',
            name='course_content',
            field=models.TextField(default=''),
        ),
    ]
