# Generated by Django 4.2.4 on 2023-12-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0015_mathcourse_course_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
