# Generated by Django 4.2.4 on 2023-12-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0017_rename_course_module_lecture_module'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='module',
            new_name='course_module',
        ),
    ]
