# Generated by Django 4.2.4 on 2023-12-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0018_rename_module_lecture_course_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questionImg/'),
        ),
        migrations.AlterField(
            model_name='commontest',
            name='question',
            field=models.CharField(blank=True, max_length=1050, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course_module',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='adminMathTrainer.coursemodule'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
