# Generated by Django 4.2.4 on 2023-12-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0019_alter_commontest_image_alter_commontest_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontest',
            name='answer',
            field=models.CharField(max_length=550),
        ),
    ]
