# Generated by Django 4.2.4 on 2023-12-09 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0020_alter_commontest_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=550)),
                ('is_right', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=1050, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questionImg/')),
                ('explanation', models.TextField(null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminMathTrainer.lecture')),
            ],
        ),
    ]
