# Generated by Django 4.2.4 on 2023-12-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0021_answer_choicetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminMathTrainer.choicetest'),
        ),
    ]
