# Generated by Django 5.0 on 2023-12-10 06:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0023_alter_lecture_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='choicetest',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commontest',
            name='explanation',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='commontest',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
