# Generated by Django 5.0 on 2023-12-10 08:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0024_alter_answer_answer_alter_choicetest_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathcourse',
            name='course_content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
