# Generated by Django 5.0 on 2023-12-10 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0026_alter_lecture_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathcourse',
            name='like_user',
            field=models.ManyToManyField(related_name='liked_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
