# Generated by Django 5.0 on 2023-12-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminMathTrainer', '0027_mathcourse_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathcourse',
            old_name='like_user',
            new_name='user_favorites',
        ),
    ]
